version: '3'
services:
  airflow:
    image: apache/airflow:2.7.0
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=true
    ports:
      - "8081:8080"
    volumes:
      - ./dags:/opt/airflow/dags
    command: standalone
    